server:
  port: 3100

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          netflix: debug
    com:
      netflix: debug

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
    fetch-registry: true

info:
  app:
    name: Account Example Application
    version: 1.0.0
    discription: This is a demo project for eurkea